/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class webcam_WebCam */

#ifndef _Included_webcam_WebCam
#define _Included_webcam_WebCam

extern "C" {
    

/*
 * Class:     webcam_WebCam
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_webcam_WebCam_initialize
  (JNIEnv *, jobject);

/*
 * Class:     webcam_WebCam
 * Method:    uninitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_webcam_WebCam_uninitialize
  (JNIEnv *, jobject);

/*
 * Class:     webcam_WebCam
 * Method:    openCamera
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_webcam_WebCam_NopenCamera
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     webcam_WebCam
 * Method:    closeCamera
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_webcam_WebCam_closeCamera
  (JNIEnv *, jobject);

/*
 * Class:     webcam_WebCam
 * Method:    capture
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_webcam_WebCam_capture
  (JNIEnv *, jobject, jstring);

/*
 * Class:     webcam_WebCam
 * Method:    capture
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_webcam_WebCam_captureFrame
  (JNIEnv *, jobject);
    
/*
 * Class:     webcam_WebCam
 * Method:    isCameraOpen
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_webcam_WebCam_isCameraOpen
  (JNIEnv *, jobject);

    
HRESULT setImageDimensions (int width, int height);
    
void throwWebCamException(JNIEnv *, const char *);

}

#endif
